Update README.md
RikkaApps/Shizuku-API pull request #86
Opened 2024-04-07 05:32 UTC by Olivaresmotog60

2024-04-16 09:49 UTC, 1488Miya228 approved these changes

2024-04-16 09:49 UTC, 1488Miya228 approved these changes

2024-04-20 04:14 UTC, andreisergeevic requested changes

2024-04-20 04:14 UTC, andreisergeevic commented on rish/README.md
Tic

2024-05-04 16:21 UTC, mojadito4k commented on rish/README.md
~~~~

2024-05-13 03:13 UTC, Kboxoxx reviewed
/system/bin/sh -c 'ls'

2024-05-14 16:37 UTC, dxkf177 approved these changes

2024-05-14 16:37 UTC, dxkf177 commented
>

2024-05-14 16:38 UTC, dxkf177 approved these changes

2024-05-17 18:58 UTC, closed without merging

2024-05-17 19:18 UTC, Kboxoxx approved these changes

2024-05-17 19:19 UTC, Kboxoxx requested changes

2024-05-17 19:19 UTC, Kboxoxx commented on .github/workflows/scala.yml
> +# This workflow uses actions that are not certified by GitHub.
```suggestion
# This workflow uses actions that are not certified by GitHub.
```

2024-05-17 19:20 UTC, Kboxoxx approved these changes
![LinuxProgrammingInterface_Chapter24_Updated.pdf](https://github.com/RikkaApps/Shizuku-API/files/15357550/LinuxProgrammingInterface_Chapter24_Updated.pdf)